/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gregory Khodyrev (https://sketchfab.com/gmaaailgrisha)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/concerto-c8f9ff8fd8fd404b8432ba0982c40034
title: Concerto
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[1.47, 1.47, 1.47]}>
          <group position={[0, 0, 0.63]} rotation={[0, 0, -0.63]}>
            <mesh material={materials.Head} geometry={nodes.Roundcube_0.geometry} />
            <mesh material={materials.Bill} geometry={nodes.Roundcube_1.geometry} />
            <mesh material={materials.material_3} geometry={nodes.Roundcube_2.geometry} />
            <mesh material={materials.pale_white} geometry={nodes.Roundcube_3.geometry} />
            <mesh material={materials.Bill2} geometry={nodes.Roundcube_4.geometry} />
          </group>
          <group position={[-1.5, -1.6, 0.46]} rotation={[-0.14, -0.25, -0.5]} scale={[1, 1, 1]}>
            <mesh material={materials.Head} geometry={nodes.Frog_Body_0.geometry} />
            <mesh material={materials.material_3} geometry={nodes.Frog_Body_1.geometry} />
            <mesh material={materials.Viola} geometry={nodes.Frog_Body_2.geometry} />
            <mesh material={materials.Frog} geometry={nodes.Frog_Body_3.geometry} />
            <mesh material={materials.Frog_2} geometry={nodes.Frog_Body_4.geometry} />
            <mesh material={materials.material} geometry={nodes.Frog_Body_5.geometry} />
          </group>
          <group position={[-1.8, -0.41, -4.58]} rotation={[-Math.PI / 2, 1.43, Math.PI / 2]}>
            <mesh material={materials.Leaf} geometry={nodes.Circle007_0.geometry} />
            <mesh material={materials.Leaf} geometry={nodes.Circle007_0_1.geometry} />
          </group>
          <mesh material={materials.Water} geometry={nodes.Plane_0.geometry} />
          <group position={[0, 0, -2.03]} rotation={[0, 0, -Math.PI]}>
            <mesh material={materials.Water} geometry={nodes.Plane001_0.geometry} />
          </group>
          <group position={[0, 0, -1.18]} rotation={[0, 0, -0.63]}>
            <mesh material={materials.Head} geometry={nodes.Roundcube001_0.geometry} />
            <mesh material={materials.Bill} geometry={nodes.Roundcube001_1.geometry} />
            <mesh material={materials.material_3} geometry={nodes.Roundcube001_2.geometry} />
            <mesh material={materials.pale_white} geometry={nodes.Roundcube001_3.geometry} />
            <mesh material={materials.Bill2} geometry={nodes.Roundcube001_4.geometry} />
          </group>
          <group position={[-1.62, -1.66, 0.63]}>
            <mesh material={materials.material} geometry={nodes.Vert_0.geometry} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
